import {StyleSheet, Platform} from 'react-native';
import {Fonts} from '../../../interfaces/fonts.enum';

export const styles = StyleSheet.create({
  container: {
    paddingBottom: Platform.OS === 'ios' ? 0 : 8,
    borderTopWidth: 0.5,
    borderTopColor: '#e0e4e7',
    paddingHorizontal: 12,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    paddingHorizontal: 4,
    paddingVertical: 4,
    minHeight: 48,
    maxHeight: 120,
    elevation: 3,
    shadowColor: Platform.OS === 'ios' ? '#000' : '#25D366',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: Platform.OS === 'ios' ? 0.1 : 0.15,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#e8ecf0',
  },
  attachButton: {
    marginLeft: 6,
    marginRight: 4,
    marginBottom: 6,
    padding: 8,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    minWidth: 40,
    minHeight: 40,
  },
  attachButtonPressed: {
    backgroundColor: '#f5f7fa',
    transform: [{scale: 0.95}],
  },
  textInputContainer: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 8,
    justifyContent: 'center',
    minHeight: 40,
  },
  textInput: {
    fontFamily: Fonts.Helvetica,
    fontSize: 16,
    color: '#111b21',
    textAlignVertical: 'center',
    lineHeight: 20,
    paddingVertical: Platform.OS === 'ios' ? 8 : 6,
    paddingHorizontal: 4,
    minHeight: Platform.OS === 'ios' ? 36 : 32,
    maxHeight: 80,
  },
  sendButton: {
    marginLeft: 4,
    marginRight: 6,
    marginBottom: 6,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#25D366',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#25D366',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    transform: [{scale: 1}],
  },
  sendButtonPressed: {
    backgroundColor: '#1ea952',
    transform: [{scale: 0.95}],
    elevation: 2,
    shadowOpacity: 0.2,
  },
  sendButtonDisabled: {
    backgroundColor: '#a7c4a0',
    elevation: 1,
    shadowOpacity: 0.1,
  },
  microphoneButton: {
    marginLeft: 4,
    marginRight: 6,
    marginBottom: 6,
    padding: 10,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    minWidth: 44,
    minHeight: 44,
  },
  microphoneButtonPressed: {
    backgroundColor: '#f5f7fa',
    transform: [{scale: 0.95}],
  },
  sendIcon: {
    fontSize: 16,
    color: '#ffffff',
    fontFamily: Fonts.Helvetica,
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Enhanced button states
  buttonActive: {
    opacity: 1,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  // Typing indicator styles
  typingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  typingDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#8696a0',
    marginHorizontal: 1,
  },

  attachmentPreview: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f8f9fa',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e8ecf0',
  },
});
