import {StyleSheet} from 'react-native';
import {Fonts} from '../../../../interfaces/fonts.enum';
import {COLORS} from '../../../../constants/COLORS';

export const styles = StyleSheet.create({
  handleIndicator: {
    backgroundColor: COLORS.backgroundColor,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundColor,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: COLORS.backgroundColor,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E5E5',
  },
  cancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  cancelText: {
    fontSize: 17,
    fontFamily: Fonts.Helvetica,
    color: '#25D366',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontFamily: Fonts.Helvetica,
    color: '#000',
    fontWeight: '600',
  },
  headerCount: {
    fontSize: 13,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    marginTop: 1,
  },
  createButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  disabledCreateButton: {
    opacity: 0.5,
  },
  createText: {
    fontSize: 17,
    fontFamily: Fonts.Helvetica,
    color: '#25D366',
    fontWeight: '600',
  },
  disabledCreateText: {
    color: '#8E8E93',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#000',
    backgroundColor: 'transparent',
  },
  descriptionContainer: {
    marginBottom: 24,
  },
  description: {
    fontSize: 13,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    lineHeight: 18,
  },
  membersContainer: {
    flex: 1,
  },
  membersSection: {
    backgroundColor: COLORS.whiteColor,
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 8,
  },
  addMemberButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.whiteColor,
  },
  addMemberIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  addMemberText: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#000',
  },
  divider: {
    height: 0.5,
    backgroundColor: '#E5E5E5',
    marginLeft: 68,
  },
  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.whiteColor,
  },
  memberInfo: {
    flex: 1,
  },
  memberName: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#000',
  },
  memberPhone: {
    fontSize: 14,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    marginTop: 2,
  },
  removeMemberButton: {
    padding: 8,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  memberAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },

  // Contact Selection styles
  searchContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E5E5E5',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#000',
    marginLeft: 8,
  },
  infoContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.whiteColor,
    borderRadius: 10,
    marginHorizontal: 20,
  },
  infoText: {
    fontSize: 13,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    textAlign: 'center',
    lineHeight: 18,
  },
  contactsContainer: {
    flex: 1,
    flexDirection: 'row',
    marginHorizontal: 20,
  },
  contactsList: {
    flex: 1,
  },
  sectionHeader: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.whiteColor,
    borderBottomColor: COLORS.dirtyColor,
    borderRadius: 10,
  },
  contactLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarContainer: {
    marginRight: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  defaultAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    fontWeight: '600',
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#000',
    fontWeight: '400',
  },
  contactPhone: {
    fontSize: 13,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    marginTop: 2,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E5E5',
    backgroundColor: COLORS.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkedCheckbox: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  checkmark: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.whiteColor,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    color: '#8E8E93',
    textAlign: 'center',
  },

  // Legacy styles - keeping for compatibility
  title: {
    fontSize: 18,
    fontFamily: Fonts.Helvetica,
    color: 'gray',
  },
  closeButton: {
    padding: 5,
  },
  selectedContactItem: {
    backgroundColor: '#e8f5e8',
  },
  selectedIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#25D366',
    alignItems: 'center',
    justifyContent: 'center',
  },
  createButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 10,
  },
  listItemText: {
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
    flex: 1,
  },
  iconContainer: {
    backgroundColor: 'rgba(0,0,0,0.05)',
    padding: 10,
    borderRadius: 50,
  },
  selectedMembersHorizontalContainer: {
    maxHeight: 50,
    marginBottom: 15,
    paddingHorizontal: 5,
  },
  selectedMemberChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#25D366',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 20,
    marginRight: 8,
    maxWidth: 120,
  },
  selectedMemberChipText: {
    color: 'white',
    fontSize: 12,
    marginHorizontal: 6,
    flex: 1,
  },
  doneButton: {
    backgroundColor: '#25D366',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  doneButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: Fonts.Helvetica,
  },
  contactAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  contactAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  chipAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginRight: 4,
  },
  chipAvatarPlaceholder: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
});
